In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline, make_union
from tpot.builtins import StackingEstimator
from sklearn.preprocessing import FunctionTransformer
from copy import copy
#Modifier en fonction du pipelines

# Import de la bdd

In [5]:
df = pd.read_csv('C:/Users/orkad/Desktop/stage M1/datasets/datasets fonctionnels/cervus/data_cervus.csv')
#df = pd.read_csv('C:/Users/orkad/Desktop/stage M1/datasets/datasets fonctionnels/cervus/data_bos.csv')
#df = pd.read_csv('C:/Users/orkad/Desktop/stage M1/datasets/datasets fonctionnels/cervus/data_sus.csv')
df = df.rename(columns = {'Unnamed: 0': 'label'})
df = df.fillna(0)

# Rennomage des Ã©chantillons

## Choisir en fonction de la BDD (passer la cellule en mode code pour l'executer)

### Cervus

In [3]:
n = len(df.index)
x = 0
while x < n:
    a = 'cerf' in df.iloc[x,0]
    b = 'daim' in df.iloc[x,0]
    c = 'meagC' in df.iloc[x,0]
    if a == True :
        df.iloc[x,0] = 'cerf'
    elif b == True :
        df.iloc[x,0] = 'daim'
        
    elif c == True :
        df.iloc[x,0] = 'meagC'
    else:
        df.iloc[x,0] = 'Autre' 
    x = x+1

### Bos

n = len(df.index)
x = 0
while x < n:
    a = 'boeuf' in df.iloc[x,0]
    b = 'B1' in df.iloc[x,0] 
    c = 'B2' in df.iloc[x,0]
    d = 'B3' in df.iloc[x,0]
    e = 'B4' in df.iloc[x,0]
    f = 'B5' in df.iloc[x,0]
    g = 'B6' in df.iloc[x,0]
    h = 'auroch' in df.iloc[x,0]
    i = 'C1' in df.iloc[x,0]
    j = 'C2' in df.iloc[x,0]
    k = 'C3' in df.iloc[x,0]
    l = 'C4' in df.iloc[x,0]
    m = 'C5' in df.iloc[x,0]
    o = 'C6' in df.iloc[x,0]
    if a or b or c or d or e or f or g == True :
        df.iloc[x,0] = 'boeuf'
    elif h or i or j or k or l or m or o== True :
        df.iloc[x,0] = 'auroch'
    else:
        df.iloc[x,0] = 'autre' 
    x = x+1

### Sus

n = len(df.index)

x = 0
while x < n:
    a = 'porc' in df.iloc[x,0]
    b = 'sanglier' in df.iloc[x,0]
    if a == True :
        df.iloc[x,0] = 'porc'
    if b == True :
        df.iloc[x,0] = 'sanglier'
    else:
        df.iloc[x,0] = 'autre'
    x = x+1

In [6]:
df

,label,698.35785,701.33972,722.35846,728.33232,738.36675,758.3665,784.43591,785.38418,811.40606,...,4365.08859,4375.12146,4387.06383,4391.11539,4479.12101,4480.09941,4493.13648,4495.10686,4507.14868,4523.14453
0,auroch(9).s1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1236710.0,0.0
1,auroch(9).s2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1030345.0,0.0
2,auroch(9).s3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,968308.0,294259.0
3,aurochs T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,B1-1,0.0,0.0,0.0,0.0,0.0,323421.0,0.0,429004.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,meagC75,0.0,0.0,165278.0,202820.0,0.0,0.0,0.0,0.0,154355.0,...,3372383.0,0.0,478751.0,0.0,0.0,1651319.0,0.0,0.0,0.0,0.0
120,meagC76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6258022.0,0.0,498120.0,0.0,0.0,2568663.0,0.0,314859.0,0.0,0.0
121,meagC77,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2213999.0,0.0,0.0,0.0,0.0,1146087.0,0.0,0.0,0.0,0.0
122,meagC79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1723556.0,0.0,0.0,0.0,0.0,449057.0,0.0,0.0,0.0,0.0
123,meagC80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,450283.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0